environment:
  seed: 42
  num_clients: 120
  num_selected_clients: 80
  num_malicious_clients: 16
  experiment_name: "resnet18"
  attacker_full_knowledge: False
  attacker_full_dataset: False
  attack_frequency: 1
  # attack freq 0.2 means attacking for every 1/0.2=5 rounds
  prune_frequency: 0.2
  paoding: 1
  pruneconv: 0
  load_model: resnet18
  save_model_at: [20]

server:
  num_rounds: 30
  num_test_batches: 64
  aggregator:
    name: FedAvg
    #name: TrimmedMean
    #args:
    #  beta: 0.1
  global_learning_rate: -1

client:
  model_name: resnet18
  benign_training:
    num_epochs: 1
    batch_size: 24
    optimizer: Adam
    learning_rate: 0.001
  malicious:
    objective:
      name: TargetedAttack
      args:
        num_epochs: 5
        num_batch: 5
        poison_samples: 12
        optimizer: Adam
        learning_rate: 0.01
        reduce_lr: true
    evasion:
      name: NormBoundPGDEvasion
      args:
        norm_type: l_inf
        scale_factor: 30
    #multi_attacker_scale_divide: true
    backdoor:
      type: tasks
      tasks: 3
      target_label: 1
      source_label: 7
      aux_samples: -1
      augment_times: 20

dataset:
  dataset: cifar10
  data_distribution: nonIID